using LayoutParserApi.Models.Entities.Fiscal;
using LayoutParserApi.Models.Entities.Identity;
using LayoutParserApi.Services.Filters;
using LayoutParserApi.Services.Interfaces;
using LayoutParserApi.Services.Transformation.Ai;

using Microsoft.AspNetCore.Mvc;

namespace LayoutParserApi.Controllers
{
    public sealed class ApproveReleaseRequest
    {
        public string? Justification { get; set; }
    }

    public sealed class PublishReleaseRequest
    {
        public string? Environment { get; set; }
    }

    /// <summary>Corpo opcional das transições de ciclo de vida (deprecate/archive — issue #378).</summary>
    public sealed class LifecycleTransitionRequest
    {
        public string? Justification { get; set; }
    }

    /// <summary>
    /// Governança/publicação de <see cref="MappingRelease"/> — Slice 7 (issue #94, design
    /// <c>design-slice7-governanca-piloto-fiat-2026-09-01.md</c>). Último slice da fundação: promove
    /// uma release <c>test_passed</c> a <c>approved</c>/<c>published</c> com RBAC mínimo por papel de
    /// workspace, com trilha de auditoria completa em <see cref="MappingTransition"/>.
    /// </summary>
    [ApiController]
    [Route("api/workspaces/{workspaceId:guid}/mapping-releases/{releaseId:guid}")]
    public class MappingGovernanceController : ControllerBase
    {
        /// <summary>Discriminador de <c>origin</c>: release real vinda de <c>POST .../compile</c> sobre um draft.</summary>
        public const string OriginDraftCompile = "draft_compile";

        /// <summary>Discriminador de <c>origin</c>: candidato TCL/XSLT gerado automaticamente (issue #438).</summary>
        public const string OriginAutoGenerated = "auto_generated";

        // Status do lado auto-gerado aceitos em ?status= (vocabulário próprio; não colide com MappingReleaseStatus).
        private static readonly string[] GeneratedStatuses =
        {
            GeneratedMapperArtifactStatus.Ready, GeneratedMapperArtifactStatus.Generating, GeneratedMapperArtifactStatus.Stale,
        };

        private readonly IMappingReleaseStore _releaseStore;
        private readonly IGeneratedMapperListService _generatedList;
        private readonly ICurrentUser _currentUser;
        private readonly ILogger<MappingGovernanceController> _logger;

        public MappingGovernanceController(
            IMappingReleaseStore releaseStore,
            IGeneratedMapperListService generatedList,
            ICurrentUser currentUser,
            ILogger<MappingGovernanceController> logger)
        {
            _releaseStore = releaseStore;
            _generatedList = generatedList;
            _currentUser = currentUser;
            _logger = logger;
        }

        /// <summary>
        /// Lista releases do workspace, paginado (issue #198 do front — não havia NENHUM endpoint de
        /// descoberta: os 3 endpoints de governança abaixo exigem <c>releaseId</c> já conhecido).
        /// Rota própria (sem <c>{releaseId}</c>) via <c>~/</c> porque a rota base do controller já fixa
        /// esse segmento. Qualquer papel do workspace pode ler — só as mutações (approve/publish/
        /// rollback) exigem papel elevado.
        /// <para>
        /// Filtros opcionais (issue #377), combináveis: <c>status</c> (um valor do ciclo de vida —
        /// <c>draft_compiled</c>, <c>test_passed</c>, <c>test_failed</c>, <c>in_review</c>,
        /// <c>approved</c>, <c>published</c>, <c>deprecated</c>, <c>archived</c>), <c>draftId</c> (GUID)
        /// e <c>environment</c>. Valor de <c>status</c> fora do ciclo de vida ou <c>draftId</c> que não
        /// seja GUID retornam <c>400</c>. Sem filtro, o resultado é idêntico ao comportamento anterior.
        /// </para>
        /// <para>
        /// <b>Listagem unificada (issue #438, ADR <c>adr-unificacao-generated-artifact-mapping-release.md</c>,
        /// opção b).</b> Além das releases reais (<c>origin: "draft_compile"</c>), a lista traz os
        /// candidatos TCL/XSLT gerados automaticamente (<c>origin: "auto_generated"</c>). Nada migra de
        /// tabela. Item auto-gerado: <c>{ origin, mapperGuid, mapperName?, status, validationBasis?,
        /// coverage?, generatedAt?, correlationId?, detailUrl, catalogId?, catalogDetailUrl? }</c> — SEM <c>releaseId</c>/<c>draftId</c>/
        /// <c>testRunSummary</c>/<c>approvedByUserId</c>/<c>engine</c> (omitidos, não <c>null</c>).
        /// <c>validationBasis</c> é <c>declared_dsl</c>: cobertura contra o DSL declarado, NUNCA execução
        /// real (Fiscal Test Lab). O conteúdo TCL/XSLT NÃO vem na lista (mesmo padrão das releases):
        /// use <c>detailUrl</c> (<c>GET .../mappings/{mapperGuid}/generated-transformation</c>). Itens
        /// auto-gerados não são elegíveis a approve/publish/rollback (esses só aceitam <c>releaseId</c>).
        /// </para>
        /// <para>
        /// <b>Catálogo unificado (issue #634, aditivo).</b> Itens <c>auto_generated</c> já indexados em
        /// <c>api/mapping-catalog</c> trazem <c>catalogId</c> (GUID opaco, referência única — a mesma do portal e do
        /// parser de TXT) e <c>catalogDetailUrl</c> (<c>/api/mapping-catalog/items/{catalogId}</c>). Os dois campos
        /// são OMITIDOS (não <c>null</c>) enquanto o item não estiver no índice (sync desligado ou ainda não rodou).
        /// <c>mapperGuid</c> permanece por compatibilidade mas está <b>deprecated</b>: não é único entre projetos —
        /// migre para <c>catalogId</c>. Nenhum campo existente mudou.
        /// </para>
        /// <para>
        /// Filtros nessa unificação: <c>origin</c> (<c>draft_compile</c> | <c>auto_generated</c>, ausente =
        /// ambos). <c>draftId</c> e <c>environment</c> só existem para release real — quando informados,
        /// os auto-gerados são EXCLUÍDOS. <c>status</c> aceita o ciclo de vida da release (exclui os
        /// auto-gerados) OU <c>ready</c>/<c>generating</c>/<c>stale</c> (exclui as releases; <c>stale</c>
        /// não é persistido, então a listagem não devolve nada para ele — só o detalhe o calcula).
        /// </para>
        /// <para>
        /// Paginação combinada: sequência única "releases reais (mais recentes primeiro) e depois os
        /// auto-gerados (mais recentes primeiro)"; <c>totalCount</c> soma as duas fontes e cada página
        /// tem no máximo <c>pageSize</c> itens. Se o store de auto-gerados falhar, a lista devolve só as
        /// releases reais (falha logada) e <c>autoGeneratedUnavailable</c> = <c>true</c>.
        /// </para>
        /// <para>
        /// <b>Vínculo mapper→workspace (#417) — decisão PROVISÓRIA (a), sem isolamento:</b> todo artefato
        /// gerado aparece para todo workspace, porque o catálogo Sysmiddle já é org-wide
        /// (<c>AllowedPackageGuids</c>). Não fecha o caminho para isolar depois: o ponto único de
        /// filtragem é <see cref="IGeneratedMapperListService"/>.
        /// </para>
        /// </summary>
        /// <remarks>
        /// RBAC: qualquer papel de membro (<c>owner</c>/<c>fiscal_admin</c>/<c>mapper</c>/
        /// <c>reviewer</c>/<c>operator</c>/<c>viewer</c>). Não-membro ou sem identidade → 404.
        /// Só aceita <c>page</c>/<c>pageSize</c> — não há filtro por <c>status</c>/<c>draftId</c>/
        /// <c>environment</c> ainda (issue #377, backlog).
        /// </remarks>
        /// Aceita <c>page</c>/<c>pageSize</c> e os filtros opcionais <c>status</c>/<c>draftId</c>/
        /// <c>environment</c> (issue #377).
        /// </remarks>
        /// <param name="workspaceId">Workspace dono das releases.</param>
        /// <param name="page">Página (1-based). Default 1.</param>
        /// <param name="pageSize">Tamanho da página (1..100). Default 20.</param>
        /// <param name="status">Opcional. Filtra por status do ciclo de vida da release.</param>
        /// <param name="draftId">Opcional. Filtra pelas releases geradas a partir do draft informado (GUID).</param>
        /// <param name="environment">Opcional. Filtra pelo ambiente de publicação da release (exclui auto-gerados).</param>
        /// <param name="origin">Opcional. <c>draft_compile</c> ou <c>auto_generated</c>; ausente = ambos.</param>
        /// <param name="cancellationToken">Token de cancelamento.</param>
        /// <response code="200"><c>{ items[], page, pageSize, totalCount, autoGeneratedUnavailable }</c>. Cada item traz <c>origin</c> (<c>draft_compile</c> | <c>auto_generated</c>); campos que não se aplicam à origem são omitidos.</response>
        /// <response code="400"><c>page</c>/<c>pageSize</c> fora do intervalo, <c>status</c> ou <c>origin</c> inválidos, ou <c>draftId</c> que não é GUID.</response>
        /// <response code="404">Sem identidade ou não é membro do workspace (fail-closed; não existe 401).</response>
        [HttpGet("~/api/workspaces/{workspaceId:guid}/mapping-releases")]
        [RequireWorkspaceRole(WorkspaceRoleLevel.Viewer)]
        public async Task<IActionResult> List(
            Guid workspaceId,
            [FromQuery] int page = 1,
            [FromQuery] int pageSize = 20,
            [FromQuery] string? status = null,
            [FromQuery] string? draftId = null,
            [FromQuery] string? environment = null,
            [FromQuery] string? origin = null,
            CancellationToken cancellationToken = default)
        {
            if (page < 1)
                return BadRequest(new { error = "\"page\" deve ser >= 1." });

            if (pageSize < 1 || pageSize > 100)
                return BadRequest(new { error = "\"pageSize\" deve estar entre 1 e 100." });

            // Valida "status" contra o ciclo de vida da release (issue #377) — valor livre não chega ao SQL.
            var statusIsRelease = !string.IsNullOrWhiteSpace(status) && MappingReleaseStatus.All.Contains(status);
            var statusIsGenerated = !string.IsNullOrWhiteSpace(status) && GeneratedStatuses.Contains(status);
            if (!string.IsNullOrWhiteSpace(status) && !statusIsRelease && !statusIsGenerated)
                return BadRequest(new { error = $"\"status\" inválido. Valores aceitos: {string.Join(", ", MappingReleaseStatus.All.Concat(GeneratedStatuses))}." });

            if (!string.IsNullOrWhiteSpace(origin) && origin != OriginDraftCompile && origin != OriginAutoGenerated)
                return BadRequest(new { error = $"\"origin\" inválido. Valores aceitos: {OriginDraftCompile}, {OriginAutoGenerated}." });

            // "draftId" é recebido como string para devolver 400 com mensagem PT-BR (e não o 400
            // genérico do model binder) quando não for um GUID.
            Guid? draftIdFilter = null;
            if (!string.IsNullOrWhiteSpace(draftId))
            {
                if (!Guid.TryParse(draftId, out var parsedDraftId))
                    return BadRequest(new { error = "\"draftId\" deve ser um GUID válido." });
                draftIdFilter = parsedDraftId;
            }

            var environmentFilter = string.IsNullOrWhiteSpace(environment) ? null : environment;

            // Quem entra na união (ver XML doc): filtros exclusivos de release excluem os auto-gerados
            // e status do vocabulário de auto-gerado exclui as releases.
            var includeReleases = origin != OriginAutoGenerated && !statusIsGenerated;
            var includeGenerated = origin != OriginDraftCompile && draftIdFilter is null
                && environmentFilter is null && !statusIsRelease;

            // Sequência única: releases primeiro, depois auto-gerados. offset é sempre múltiplo de
            // pageSize, então a página de releases do store continua alinhada como antes da unificação.
            var offset = (page - 1) * pageSize;

            IReadOnlyList<MappingReleaseDetail> releaseItems = Array.Empty<MappingReleaseDetail>();
            var releaseTotal = 0;
            if (includeReleases)
            {
                (releaseItems, releaseTotal) = await _releaseStore.ListByWorkspaceAsync(
                    workspaceId, page, pageSize, statusIsRelease ? status : null, draftIdFilter, environmentFilter, cancellationToken);
            }

            var generatedPage = GeneratedMapperListPage.Empty;
            if (includeGenerated)
            {
                generatedPage = await _generatedList.ListAsync(
                    statusIsGenerated ? status : null,
                    skip: Math.Max(0, offset - releaseTotal),
                    take: pageSize - releaseItems.Count,
                    cancellationToken);
            }

            var items = releaseItems.Select(ToReleaseResponse)
                .Concat(generatedPage.Items.Select(g => ToGeneratedResponse(workspaceId, g)))
                .ToList();

            return Ok(new
            {
                items,
                page,
                pageSize,
                totalCount = releaseTotal + generatedPage.TotalCount,
                autoGeneratedUnavailable = !generatedPage.Available,
            });
        }

        /// <summary><c>test_passed → in_review → approved</c>. Bloqueado se a release estiver <c>test_failed</c> (ou qualquer status diferente de <c>test_passed</c>).</summary>
        /// <remarks>
        /// RBAC: exige papel <c>reviewer</c> ou <c>fiscal_admin</c> no workspace da rota. Sem
        /// membership → 404; papel insuficiente → 403. Corpo exige <c>justification</c> (422 se ausente).
        /// </remarks>
        [HttpPost("approve")]
        [RequireWorkspaceRole(WorkspaceRoleLevel.Admin)]
        public async Task<IActionResult> Approve(Guid workspaceId, Guid releaseId, [FromBody] ApproveReleaseRequest request, CancellationToken cancellationToken)
        {
            if (_currentUser.UserId is not Guid userId)
                return NotFound();

            if (string.IsNullOrWhiteSpace(request.Justification))
                return UnprocessableEntity(new { error = "Campo \"justification\" é obrigatório para aprovar uma release." });

            var release = await _releaseStore.GetReleaseIfMemberAsync(releaseId, userId, cancellationToken);
            if (release == null || release.WorkspaceId != workspaceId)
                return NotFound();

            try
            {
                var approved = await _releaseStore.ApproveAsync(releaseId, userId, request.Justification, cancellationToken);
                return Ok(ToReleaseResponse(approved));
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogWarning(ex, "Aprovação recusada para release {ReleaseId}.", releaseId);
                return UnprocessableEntity(new { error = ex.Message });
            }
        }

        /// <summary><c>approved → published</c>. Congela os artefatos — edição posterior exige nova revisão (novo <see cref="MappingRelease"/>).</summary>
        /// <remarks>RBAC: exige papel <c>fiscal_admin</c> ou <c>owner</c> no workspace da rota. Sem membership → 404; papel insuficiente → 403.</remarks>
        [HttpPost("publish")]
        [RequireWorkspaceRole(WorkspaceRoleLevel.Admin)]
        public async Task<IActionResult> Publish(Guid workspaceId, Guid releaseId, [FromBody] PublishReleaseRequest? request, CancellationToken cancellationToken)
        {
            if (_currentUser.UserId is not Guid userId)
                return NotFound();

            var environment = string.IsNullOrWhiteSpace(request?.Environment) ? "production" : request.Environment;

            var release = await _releaseStore.GetReleaseIfMemberAsync(releaseId, userId, cancellationToken);
            if (release == null || release.WorkspaceId != workspaceId)
                return NotFound();

            try
            {
                var published = await _releaseStore.PublishAsync(releaseId, userId, environment, cancellationToken);
                return Ok(ToReleaseResponse(published));
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogWarning(ex, "Publicação recusada para release {ReleaseId}.", releaseId);
                return UnprocessableEntity(new { error = ex.Message });
            }
        }

        /// <summary>Reverte a release publicada para a publicação anterior. Idempotente — repetir a chamada é no-op.</summary>
        /// <remarks>RBAC: exige papel <c>fiscal_admin</c> ou <c>owner</c> no workspace da rota. Sem membership → 404; papel insuficiente → 403.</remarks>
        [HttpPost("rollback")]
        [RequireWorkspaceRole(WorkspaceRoleLevel.Admin)]
        public async Task<IActionResult> Rollback(Guid workspaceId, Guid releaseId, CancellationToken cancellationToken)
        {
            if (_currentUser.UserId is not Guid userId)
                return NotFound();

            var release = await _releaseStore.GetReleaseIfMemberAsync(releaseId, userId, cancellationToken);
            if (release == null || release.WorkspaceId != workspaceId)
                return NotFound();

            try
            {
                var rolledBack = await _releaseStore.RollbackAsync(releaseId, userId, cancellationToken);
                return Ok(ToReleaseResponse(rolledBack));
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogWarning(ex, "Rollback recusado para release {ReleaseId}.", releaseId);
                return UnprocessableEntity(new { error = ex.Message });
            }
        }

        /// <summary>
        /// <c>published → deprecated</c> — deprecação manual (issue #378). A release deixa de ser a
        /// publicação corrente mas continua consultável/auditável. Corpo opcional <c>justification</c>.
        /// </summary>
        /// <remarks>
        /// RBAC: exige papel <c>fiscal_admin</c> ou <c>owner</c> no workspace da rota. Sem membership → 404;
        /// papel insuficiente → 403. Transição inválida (status de origem ≠ <c>published</c>) → 422 com
        /// mensagem PT-BR. Idempotente: re-deprecar uma release já <c>deprecated</c> é no-op (200).
        /// </remarks>
        [HttpPost("deprecate")]
        [RequireWorkspaceRole(WorkspaceRoleLevel.Admin)]
        public async Task<IActionResult> Deprecate(Guid workspaceId, Guid releaseId, [FromBody] LifecycleTransitionRequest? request, CancellationToken cancellationToken)
        {
            if (_currentUser.UserId is not Guid userId)
                return NotFound();

            var release = await _releaseStore.GetReleaseIfMemberAsync(releaseId, userId, cancellationToken);
            if (release == null || release.WorkspaceId != workspaceId)
                return NotFound();

            try
            {
                var deprecated = await _releaseStore.DeprecateAsync(releaseId, userId, request?.Justification, cancellationToken);
                return Ok(ToReleaseResponse(deprecated));
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogWarning(ex, "Deprecação recusada para release {ReleaseId}.", releaseId);
                return UnprocessableEntity(new { error = ex.Message });
            }
        }

        /// <summary>
        /// <c>deprecated → archived</c> (também aceita <c>test_failed</c>/<c>in_review</c> abandonados
        /// como origem — issue #378). Estado terminal: a release fica só para histórico/auditoria.
        /// Corpo opcional <c>justification</c>.
        /// </summary>
        /// <remarks>
        /// RBAC: exige papel <c>fiscal_admin</c> ou <c>owner</c> no workspace da rota. Sem membership → 404;
        /// papel insuficiente → 403. Transição inválida (origem fora de <c>deprecated</c>/<c>test_failed</c>/
        /// <c>in_review</c> — ex.: uma <c>published</c>, que precisa ser deprecada antes) → 422 com mensagem
        /// PT-BR. Idempotente: re-arquivar uma release já <c>archived</c> é no-op (200).
        /// </remarks>
        [HttpPost("archive")]
        [RequireWorkspaceRole(WorkspaceRoleLevel.Admin)]
        public async Task<IActionResult> Archive(Guid workspaceId, Guid releaseId, [FromBody] LifecycleTransitionRequest? request, CancellationToken cancellationToken)
        {
            if (_currentUser.UserId is not Guid userId)
                return NotFound();

            var release = await _releaseStore.GetReleaseIfMemberAsync(releaseId, userId, cancellationToken);
            if (release == null || release.WorkspaceId != workspaceId)
                return NotFound();

            try
            {
                var archived = await _releaseStore.ArchiveAsync(releaseId, userId, request?.Justification, cancellationToken);
                return Ok(ToReleaseResponse(archived));
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogWarning(ex, "Arquivamento recusado para release {ReleaseId}.", releaseId);
                return UnprocessableEntity(new { error = ex.Message });
            }
        }

        /// <summary>Item <c>origin: "auto_generated"</c> — só os campos que existem no fluxo automático (omitidos quando nulos; ver XML doc de <see cref="List"/>).</summary>
        private static object ToGeneratedResponse(Guid workspaceId, GeneratedMapperListItem item) => new
        {
            origin = OriginAutoGenerated,
            mapperGuid = item.MapperGuid,
            mapperName = item.MapperName,
            status = item.Status,
            validationBasis = item.ValidationBasis,
            coverage = item.Coverage,
            generatedAt = item.GeneratedAt,
            correlationId = item.CorrelationId,
            detailUrl = $"/api/workspaces/{workspaceId}/mappings/{Uri.EscapeDataString(item.MapperGuid)}/generated-transformation",
            // Issue #634 (aditivo): referência única do catálogo; omitidos enquanto o item não está indexado.
            catalogId = item.CatalogId,
            catalogDetailUrl = item.CatalogId is Guid cid ? $"/api/mapping-catalog/items/{cid}" : null,
        };

        private static MappingReleaseGovernanceResponse ToReleaseResponse(MappingReleaseDetail release) => new()
        {
            Origin = OriginDraftCompile,
            ReleaseId = release.ReleaseId,
            WorkspaceId = release.WorkspaceId,
            DraftId = release.DraftId,
            Engine = release.Engine,
            Status = release.Status,
            Environment = release.Environment,
            ApprovedByUserId = release.ApprovedByUserId,
            ApprovedAt = release.ApprovedAt,
            ApprovalJustification = release.ApprovalJustification,
            PublishedByUserId = release.PublishedByUserId,
            PublishedAt = release.PublishedAt,
            PreviousPublishedReleaseId = release.PreviousPublishedReleaseId,
            CorrelationId = release.CorrelationId,
            ETag = release.ETag,
        };
    }
}
